### ISSUE TITLE
Terminal logs "Modal failed :/" when clicking select buttons, and no selection window is opened

### ISSUE THREAD

**Issue by sourcelocation** [brandonplank/iPAPatcher#11]
The title says it all. I am running as root. If I run iPAPatcher not as root, the window shows up.
Log in case you need it:
`exerhythm@MacBook-Pro-2017 MacOS % sudo /Applications/iPAPatcher.app/Contents/MacOS/iPAPatcher`
`Modal failed :/`

**Comment by brandonplank** [comment]
What macOS version?

**Comment by sourcelocation** [comment]
macOS Catalina, latest one

**Comment by sourcelocation** [comment]
Oh, I just restarted my MacBook and everything works now. The power of restarting, I guess...
