### ISSUE TITLE
[Feature request] prompt for admin password (instead of requiring manual call of "sudo")

### ISSUE THREAD

**Issue by idolize** [brandonplank/iPAPatcher#14]
Given that the application needs root/admin permissions to do it's job it would be nice if it could just prompt the user for their admin password instead of failing and requiring it to be launched via the commandline with "sudo".

Here are some resources I found online on how to do this:

- Apple docs: https://developer.apple.com/documentation/security/authorization_services
- Example code: https://github.com/potionfactory/LetsMove/blob/2b13778d3b3ae2515c8d7e71fe60dd063412f50d/PFMoveApplication.m#L419-L491

**Comment by brandonplank** [comment]
Good idea!

**Comment by brandonplank** [comment]
Your wish is my command! Added in 1.0
