### ISSUE TITLE
Error: The tweak you entered is not in the correct format.

### ISSUE THREAD

**Issue by BreckenLusk** [brandonplank/iPAPatcher#15]
I keep getting an error that the tweak I'm selecting, an Among Us! Mod Menu, which is in the form of a .deb, is in an incorrect format. I've extracted it and upon inspection it appears to be formatted correctly, just like every other tweak.

**Comment by aprunet** [comment]
Had the same issue, apparently I was missing the dpkg dependency so I've installed it by running 'brew install dpkg' in terminal and now I can patch iPAs

**Comment by brandonplank** [comment]
This should now be fixed in 1.0.
