### ISSUE TITLE
brew error becouse SU user

### ISSUE THREAD

**Issue by colofdurty** [brandonplank/iPAPatcher#16]
respurce path: /Applications/iPAPatcher.app/Contents/Resources/
optool /Applications/iPAPatcher.app/Contents/Resources/optool
fixed dylib path: /Users/a5/Desktop/tinder/honeybee_1.1.deb
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
sh: /usr/local/bin/dpkg: No such file or directory

**Comment by brandonplank** [comment]
Should be fixed in 1.0
