### ISSUE TITLE
Can't generate patched IPA

### ISSUE THREAD

**Issue by Waze0613** [brandonplank/iPAPatcher#17]
Version used : 0.7

The tool is saying : 
Patching finished, the new iPA should now be in your downloads folder!

But in CMD we can see the following : 

`/Applications/iPAPatcher.app/Contents/Resources/temp/Payload/Parchisi Star.app
/Applications/iPAPatcher.app/Contents/Resources/temp/Payload/Parchisi Star.app
plutil -convert xml1 -o - /Applications/iPAPatcher.app/Contents/Resources/temp/Payload/Parchisi Star.app/Info.plist|grep -A1 Exec|tail -n1|cut -f2 -d\>|cut -f1 -d\<
temp/Payload/Parchisi St
mkdir: Star.app: No such file or directory
START====
/Applications/iPAPatcher.app/Contents/Resources/libsubstitute.0.dylib
/Applications/iPAPatcher.app/Contents/Resources/libsubstitute.dylib
/Applications/iPAPatcher.app/Contents/Resources/CydiaSubstrate.framework
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
2020-10-26 16:41:48.395 iPAPatcher[2692:1366674] array:(
    "",
    Applications,
    "iPAPatcher.app",
    Contents,
    Resources,
    temp,
    deb,
    Library,
    MobileSubstrate,
    DynamicLibraries,
    "star.dylib"
)
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: more than one input file specified (Star.app/Dylibs/star.dylib and /Applications/iPAPatcher.app/Contents/Resources/temp/Payload/Parchisi)
Usage: /Library/Developer/CommandLineTools/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
	zip warning: name not matched: St.ipa
zip I/O error: No such file or directory
zip error: Could not create output file `

**Comment by brandonplank** [comment]
Should be fixed in release 1.0
