### ISSUE TITLE
App crash during launch on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by harshanand120** [brandonplank/iPAPatcher#21]
App crashes during launch on macOS 11.0.1. Also 'App Damaged, move to bin' is shown.

![Screenshot 2020-11-08 at 11 24 06 AM](https://user-images.githubusercontent.com/42275916/98458062-ec773f80-21b4-11eb-9e78-06e4525ada49.jpg)

**Comment by harshanand120** [comment]
This prompt shows up every time the app is launched, then it crashes.
![image](https://user-images.githubusercontent.com/42275916/98458117-6c9da500-21b5-11eb-8f05-3a636e85668a.jpeg)

**Comment by brandonplank** [comment]
Ok, so i think apple flagged the app as malware, take a look at the source code as it is nothing as such.

Try to compile it yourself and run the latest build.

**Comment by brandonplank** [comment]
Just pushed a full 1.0 release, probably will not maintain it anymore, someone else may have to. I figured I might as well push all of my changes, re open if issue still persists
