### ISSUE TITLE
Patching debs fails

### ISSUE THREAD

**Issue by niclimcy** [brandonplank/iPAPatcher#23]
I’m trying to patch the Youtube app with https://github.com/PoomSmart/YTUHD but everytime I tried patching with the deb tweak, I am met with this error:
The patching process has failed

This is the following console log that seems to be the issue:
`default 22:01:35.596323+0800 iPAPatcher Warning: Expected min height of view: (<NSButton: 0x7fcde960a9d0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation. `

**Comment by gotzlotz** [comment]
I was able to patch a Cercube.ipa with YTUHD. But no luck with a regular youtube.ipa.

**Comment by niclimcy** [comment]
I guess I was missing dependencies?

**Comment by niclimcy** [comment]
> I was able to patch a Cercube.ipa with YTUHD. But no luck with a regular youtube.ipa.

You have to find the decrypted version I guess

**Comment by bingoxo** [comment]
Did you manage to do it ?
