### ISSUE TITLE
No IPA is generated

### ISSUE THREAD

**Issue by tomlube** [brandonplank/iPAPatcher#3]
after going through all the steps, no IPA ends up being generated in the downloads folder. It also never asks for disk access to the downloads folder so I'm assuming that's part of the problem.

Xcode command line tools/zip/dpkg installed.

EDIT: Running application as sudo fixes this issue.

**Comment by Aerozolic** [comment]
Tried running as sudo but I still can't find the built ipa.

**Comment by tomlube** [comment]
did you get any output in the terminal window?

**Comment by Aerozolic** [comment]
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Applications/iPAPatcher.app/Contents/Resources/temp/Payload/*.app/Dylibs/LyricationFetchingAgent.dylib (No such file or directory)
	zip warning: name not matched: Payload/

zip error: Nothing to do! (try: zip -r /Users/xxx/Downloads/temp/Payload/*.app.ipa . -i Payload/)
Running rm -rf /Applications/iPAPatcher.app/Contents/Resources/temp

**Comment by tomlube** [comment]
remove the space out of your IPA filename

**Comment by brandonplank** [comment]
Yep, 0.4 will fix this, will be released in a few minutes

**Comment by tomlube** [comment]
> Yep, 0.4 will fix this, will be released in a few minutes

Unrelated, but is

Warning: Expected min height of view: (<NSButton: 0x7fe62cdc9000>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

Expected output?
